export const UPDATE_MOVIES = 'UPDATE_MOVIES';
export const SET_CURRENT_MOVIE = 'SET_CURRENT_MOVIE';

export const UPDATE_PLANETS = 'UPDATE_PLANETS';
export const SET_CURRENT_PLANET = 'SET_CURRENT_PLANET';
export const LOADING_PLANETS = 'LOADING_PLANETS';